dist: xenial
language: node_js
# node version is specified using the .nvmrc file
cache: npm
before_install:
  - npm install -g greenkeeper-lockfile@1
before_script:
  - greenkeeper-lockfile-update
after_script:
  - greenkeeper-lockfile-upload
addons:
  firefox: latest
  chrome: stable
  apt:
    update: true
    # libav-tools is needed by firefox for h.264 support on linux
    packages:
      libav-tools
services:
  - xvfb
