dist: xenial
language: node_js
# node version is specified using the .nvmrc file
cache: npm
before_install:
  - npm install -g greenkeeper-lockfile@1
before_script:
  # pulseaudio is needed for dockerized chrome since it has a dummy sink and
  # the dummy audio ALSA kernel module isn't loaded by Travis
  # libavcodec54 is needed by firefox for h.264 support
  - test -z $BROWSER_STACK_ACCESS_KEY && sudo apt-get install --no-install-recommends pulseaudio libavcodec54 && pulseaudio -D || echo "skipping"
  - greenkeeper-lockfile-update
after_script:
  - greenkeeper-lockfile-upload
addons:
  firefox: latest
  chrome: stable
  apt:
services:
  - xvfb
