sudo: false
dist: trusty
language: node_js
cache:
  directories:
    - node_modules
before_script:
  # pulseaudio is needed for dockerized chrome since it has a dummy sink and
  # the dummy audio ALSA kernel module isn't loaded by Travis
  # libavcodec54 is needed by firefox for h.264 support
  - sudo apt-get install --no-install-recommends pulseaudio libavcodec54
  - pulseaudio -D
addons:
  chrome: stable
  firefox: latest
