@startuml

header PlaylistLoader sequences
title PlaylistLoader sequences: Child Manifest Video-Only

Participant "MasterPlaylistController" as MPC #green
Participant "PlaylistLoader: constructor" as PLc
Participant "PL: load()" as load
Participant "PL: start()" as start
Participant "MasterPlaylistLoader\nloadedplaylist handler" as lpH
Participant "MasterPlaylistLoader\nloadedmetadata handler" as lmH
  note over lmH, lpH #white: This is located in the MasterPlaylistController
Participant "media()" as media
Participant "external server" as ext #red
Participant "m3u8Parser" as parser #orange
Participant "haveMetadata()" as haveMetadata
Participant "mainSegmentLoader" as SL #blue
Participant "mediaGroups" as mG #purple

== Initialization ==

MPC -> PLc : setting up MasterPlaylistLoader
note left #lightyellow
  sets up mediaupdatetimeout
  handler for live playlist staleness
end note
note over PLc #lightgray: state = 'HAVE_NOTHING'

MPC -> load: calls

load -> start : calls
note left: not started yet
note over start #lightgray: started = true

== Requesting media ===

start -> ext: xhr request for child manifest
ext -> start: response with child manifest

start -> parser: parse child manifest
parser -> start: object representing manifest
note over start #lightgray: state = 'HAVE_MASTER'
start -> start : infer a master playlist

start -> haveMetadata: calls
note over haveMetadata #lightgray: state = 'HAVE_METADATA'

haveMetadata -> parser: parse child manifest again
parser -> haveMetadata: object representing manifest
haveMetadata -> haveMetadata: update loader's master playlist

alt live
  haveMetadata -> haveMetadata
  note left #lightyellow: setup mediaupdatetimeout

else vod
  haveMetadata -> haveMetadata
  note left
    trigger 'loadedplaylist' on
    master loader. This does not
    end up requesting segments
    at this point.
  end note

  haveMetadata -> lpH : loadedplaylist handler
  lpH -> lpH : setup durationchange handler
end

== Requesting segments ==

start -> start
note left: "trigger 'loadedmetadata' on master loader"
start -> lmH: handling 'loadedmetadata'

alt vod and preload != 'none'
  lmH -> SL: request media segments

else vod and live with preload = 'none'
  lmH -> mG: setupMediaGroups

end

@enduml
